export const dataThree = {

        "data": {
            "itemPage": {
                "itemHeader": {
                    "id": "12942642412",
                    "name": "California Chicken Club Sandwich",
                    "imgUrl": "https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/photos/f1ee894b-f07d-4b9d-9bc9-a4aae77bc971-retina-large.jpg",
                    "imgUrlList": [],
                    "discountPricesList": [],
                    "photoCountText": null,
                    "description": "Grilled chicken breast, bacon, avocado, cheese, lettuce, tomato, mayonnaise and Kinder's mild BBQ sauce.",
                    "displayString": "+$16.95",
                    "unitAmount": 1695,
                    "currency": "USD",
                    "decimalPlaces": 2,
                    "specialInstructionsMaxLength": 0,
                    "calloutDisplayString": "#1 Most Liked",
                    "minAgeRequirement": 0,
                    "foodAlcoholConstraint": "REQUIRES_NONE",
                    "dashpassExclusiveItemDisabled": false,
                    "isDashpassExclusive": false,
                    "shouldDisplayAiDisclaimer": false,
                    "quantityLimit": 0,
                    "servingSizeDisplayString": null,
                    "banners": [],
                    "caloricInfoDisplayString": "",
                    "dietaryTagsList": [],
                    "menuId": "34652549",
                    "reviewData": {
                        "ratingDisplayString": "96% (130)",
                        "reviewCount": "3",
                        "itemReviewRankingCount": 0,
                        "consumerItemRating": {
                            "rating": {
                                "ratingType": null,
                                "ratingValue": null,
                                "__typename": "RatingInfo"
                            },
                            "ratingDisplayString": "",
                            "__typename": "ConsumerItemRating"
                        },
                        "__typename": "ReviewData"
                    },
                    "secondaryDescription": "",
                    "terms": null,
                    "badges": [],
                    "__typename": "ItemHeader"
                },
                "optionLists": [
                    {
                        "type": "extra_option",
                        "id": "8329659025",
                        "name": "Ingredients Removal Option",
                        "subtitle": "Select up to 4",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 5,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "37412400975",
                                "name": "No BBQ Sauce",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400977",
                                "name": "No Lettuce",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400978",
                                "name": "No Mayo",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400979",
                                "name": "No Tomato",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "extra_option",
                        "id": "8329659050",
                        "name": "Cheese Choice",
                        "subtitle": "Select 1",
                        "selectionNode": "single_select",
                        "minNumOptions": 1,
                        "maxNumOptions": 1,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": false,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "37412400982",
                                "name": "Cheddar Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400984",
                                "name": "Pepper Jack Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400981",
                                "name": "American Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400980",
                                "name": "No Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400983",
                                "name": "Monterey Jack Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400985",
                                "name": "Provolone Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400986",
                                "name": "Smoked Cheddar Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400987",
                                "name": "Swiss Cheese",
                                "unitAmount": 0,
                                "currency": "USD",
                                "displayString": "",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "extra_option",
                        "id": "8329659024",
                        "name": "Make it a Combo",
                        "subtitle": "Select up to 1",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 1,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "37412400945",
                                "name": "Coleslaw + BBQ Beans",
                                "unitAmount": 475,
                                "currency": "USD",
                                "displayString": "+$4.75",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400946",
                                "name": "Potato Salad & BBQ Beans",
                                "unitAmount": 475,
                                "currency": "USD",
                                "displayString": "+$4.75",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400947",
                                "name": "Mac & Cheese + BBQ Beans",
                                "unitAmount": 825,
                                "currency": "USD",
                                "displayString": "+$8.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400948",
                                "name": "Mac & Cheese + Coleslaw",
                                "unitAmount": 825,
                                "currency": "USD",
                                "displayString": "+$8.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400949",
                                "name": "Mac & Cheese + Potato Salad",
                                "unitAmount": 825,
                                "currency": "USD",
                                "displayString": "+$8.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "37412400950",
                                "name": "Mac & Cheese + Mac & Cheese",
                                "unitAmount": 925,
                                "currency": "USD",
                                "displayString": "+$9.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "extra_option",
                        "id": "8329659023",
                        "name": "BBQ Sauce Cups Addition",
                        "subtitle": "Select up to 1",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 1,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "37412400943",
                                "name": "Add 1 Extra BBQ Sauce Cup",
                                "unitAmount": 40,
                                "currency": "USD",
                                "displayString": "+$0.40",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "item",
                        "id": "recommended_option_17371972488",
                        "name": "Recommended Beverages",
                        "subtitle": "Choose up to 5",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 10,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "17371972488",
                                "name": "Dr. Pepper - 20oz Bottle",
                                "unitAmount": 425,
                                "currency": "USD",
                                "displayString": "+$4.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "17370491787",
                                "name": "Pepsi Wild Cherry - 20oz Bottle",
                                "unitAmount": 425,
                                "currency": "USD",
                                "displayString": "+$4.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "17358273102",
                                "name": "Pepsi - 20oz Bottle",
                                "unitAmount": 425,
                                "currency": "USD",
                                "displayString": "+$4.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "17371939376",
                                "name": "Pure Leaf Brewed Iced Tea Sweet - 16.9oz Bottle",
                                "unitAmount": 425,
                                "currency": "USD",
                                "displayString": "+$4.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "17370491794",
                                "name": "Starry - 20oz Bottle",
                                "unitAmount": 425,
                                "currency": "USD",
                                "displayString": "+$4.25",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "item",
                        "id": "recommended_option_12942642386",
                        "name": "Recommended Sides And Apps",
                        "subtitle": "Choose up to 3",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 10,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": null,
                        "titleLayout": null,
                        "options": [
                            {
                                "id": "12942642386",
                                "name": "Tequila Lime French Fries Regular",
                                "unitAmount": 495,
                                "currency": "USD",
                                "displayString": "+$4.95",
                                "decimalPlaces": 2,
                                "nextCursor": "eyJkbV9pZCI6Iml0ZW1fMSIsImRtX3R5cGUiOiJyZWNvbW1lbmRlZF9pdGVtIiwiZG1fdmVyc2lvbiI6MSwiY3Vyc29yX3ZlcnNpb24iOiJJVEVNX1BBR0UiLCJpdGVtSWQiOjEyOTQyNjQyMzg2LCJvcHRpb25JZCI6bnVsbCwic2VsZWN0ZWRPcmRlckl0ZW1JZCI6bnVsbCwic3RvcmVMaXRlRGF0YSI6bnVsbCwiaXNfaG9tZWdyb3duX2xveWFsdHkiOm51bGwsInBhZ2Vfc3RhY2tfdHJhY2UiOltdLCJzdG9yZUlkIjo0NDE2OSwibWVudUlkIjpudWxsLCJjYXRlZ29yeUlkIjpudWxsfQ==",
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "12942642388",
                                "name": "Brown Sugar Spice Tater Tots",
                                "unitAmount": 495,
                                "currency": "USD",
                                "displayString": "+$4.95",
                                "decimalPlaces": 2,
                                "nextCursor": "eyJkbV9pZCI6Iml0ZW1fMSIsImRtX3R5cGUiOiJyZWNvbW1lbmRlZF9pdGVtIiwiZG1fdmVyc2lvbiI6MSwiY3Vyc29yX3ZlcnNpb24iOiJJVEVNX1BBR0UiLCJpdGVtSWQiOjEyOTQyNjQyMzg4LCJvcHRpb25JZCI6bnVsbCwic2VsZWN0ZWRPcmRlckl0ZW1JZCI6bnVsbCwic3RvcmVMaXRlRGF0YSI6bnVsbCwiaXNfaG9tZWdyb3duX2xveWFsdHkiOm51bGwsInBhZ2Vfc3RhY2tfdHJhY2UiOltdLCJzdG9yZUlkIjo0NDE2OSwibWVudUlkIjpudWxsLCJjYXRlZ29yeUlkIjpudWxsfQ==",
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "12942642387",
                                "name": "Tequila Lime French Fries Sweet",
                                "unitAmount": 495,
                                "currency": "USD",
                                "displayString": "+$4.95",
                                "decimalPlaces": 2,
                                "nextCursor": "eyJkbV9pZCI6Iml0ZW1fMSIsImRtX3R5cGUiOiJyZWNvbW1lbmRlZF9pdGVtIiwiZG1fdmVyc2lvbiI6MSwiY3Vyc29yX3ZlcnNpb24iOiJJVEVNX1BBR0UiLCJpdGVtSWQiOjEyOTQyNjQyMzg3LCJvcHRpb25JZCI6bnVsbCwic2VsZWN0ZWRPcmRlckl0ZW1JZCI6bnVsbCwic3RvcmVMaXRlRGF0YSI6bnVsbCwiaXNfaG9tZWdyb3duX2xveWFsdHkiOm51bGwsInBhZ2Vfc3RhY2tfdHJhY2UiOltdLCJzdG9yZUlkIjo0NDE2OSwibWVudUlkIjpudWxsLCJjYXRlZ29yeUlkIjpudWxsfQ==",
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    },
                    {
                        "type": "item",
                        "id": "drinks_by_doubledash_option_4747871091",
                        "name": "Add Drinks With DoubleDash",
                        "subtitle": "Delivered from Safeway Beer, Wine & Spirits",
                        "selectionNode": "multi_select",
                        "minNumOptions": 0,
                        "maxNumOptions": 10,
                        "minAggregateOptionsQuantity": null,
                        "maxAggregateOptionsQuantity": null,
                        "minOptionChoiceQuantity": null,
                        "maxOptionChoiceQuantity": null,
                        "numFreeOptions": 0,
                        "isOptional": true,
                        "storeId": "2480455",
                        "titleLayout": {
                            "actionUrl": "https://www.doordash.com/drinks_menu_info_modal?O2_store_name=Safeway%20Beer%2C%20Wine%20%26%20Spirits",
                            "__typename": "MessageLayout"
                        },
                        "options": [
                            {
                                "id": "4747871091",
                                "name": "Barefoot Cellars Pinot Grigio Bottle (1.5 L)",
                                "unitAmount": 1379,
                                "currency": "USD",
                                "displayString": "+$13.79",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "10823961708",
                                "name": "Modelo Especial Mexican Lager Bottles (12 fl oz x 12 ct)",
                                "unitAmount": 2069,
                                "currency": "USD",
                                "displayString": "+$20.69",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            },
                            {
                                "id": "11565563115",
                                "name": "Coors Light American Lager Cans (12 oz x 12 ct)",
                                "unitAmount": 1494,
                                "currency": "USD",
                                "displayString": "+$14.94",
                                "decimalPlaces": 2,
                                "nextCursor": null,
                                "caloricInfoDisplayString": "",
                                "chargeAbove": 0,
                                "chargeAboveDisplayString": "",
                                "defaultQuantity": 0,
                                "dietaryTagsList": [],
                                "optionTagsList": [],
                                "minOptionChoiceQuantity": null,
                                "maxOptionChoiceQuantity": null,
                                "imgUrl": "",
                                "__typename": "FeedOption",
                                "nestedExtrasList": []
                            }
                        ],
                        "validationType": "DEFAULT",
                        "flattenedDefaultNodes": [],
                        "__typename": "OptionList"
                    }
                ],
                "presetCarousels": [],
                "itemType": "HAS_NESTED_OPTIONS",
                "itemCarousels": [],
                "itemPreferences": {
                    "id": "user_preferences_id",
                    "title": "User Preferences",
                    "specialInstructions": {
                        "title": "Add Special Instructions",
                        "characterMaxLength": 0,
                        "isEnabled": false,
                        "placeholderText": "The store has chosen not to accept special requests. Contact them directly with questions about their menus.",
                        "__typename": "ItemSpecialInstructions"
                    },
                    "substitutionPreferences": {
                        "title": "If item is unavailable",
                        "substitutionPreferencesList": [
                            {
                                "id": "OPTION_TYPE_SUBSTITUTE",
                                "displayString": "Go with merchant recommendation",
                                "isDefault": true,
                                "value": "substitute",
                                "__typename": "ItemSubstitutionPreference"
                            },
                            {
                                "id": "OPTION_TYPE_REFUND",
                                "displayString": "Refund this item",
                                "isDefault": false,
                                "value": "refund",
                                "__typename": "ItemSubstitutionPreference"
                            },
                            {
                                "id": "OPTION_TYPE_CONTACT",
                                "displayString": "Contact me",
                                "isDefault": false,
                                "value": "contact",
                                "__typename": "ItemSubstitutionPreference"
                            },
                            {
                                "id": "OPTION_TYPE_CANCEL",
                                "displayString": "Cancel the entire order",
                                "isDefault": false,
                                "value": "cancel",
                                "__typename": "ItemSubstitutionPreference"
                            }
                        ],
                        "__typename": "ItemSubstitutionPreferences"
                    },
                    "__typename": "ItemPreferences"
                },
                "additionalDescriptions": [],
                "__typename": "ItemPage"
            }
        },
        "extensions": {
            "requestInfo": {
                "version": 1,
                "requestId": "b76d96b9-a13e-4c14-a528-1f65eabc6338",
                "correlationId": "b76d96b9-a13e-4c14-a528-1f65eabc6338",
                "ddb": false
            }
        }
    }


}